name: build and push 
on:
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  buildandpush:
    name: Build and push docker
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Build dockerfile
      env:
        IMAGE_TAG: "1.0.0"
      run: docker build -t mi-app:$IMAGE_TAG  